apiVersion: apps/v1
kind: Deployment
metadata:
  name: py-cal
  labels:
    name: calculator
spec:
  replicas: 4
  selector:
    matchLabels:
      name: calculator
  template:
    metadata:
      labels:
        name: calculator
    spec:
      containers:
        - name: calculator
          image: arjunckm/pythoncalculator:207253caaa914687863243f157e757afa85afd57
          ports:
          - containerPort: 5000
      
